# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.IntegerField()),
                ('economic', models.IntegerField()),
                ('image', models.ImageField(upload_to='/home/stone/Desktop/political_faces/pictures/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='VisionAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('face', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faces.Face')),
            ],
        ),
    ]
