# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='economic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='face',
            name='social',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visionattr',
            name='x',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visionattr',
            name='y',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visionattr',
            name='z',
            field=models.CharField(max_length=50),
        ),
    ]
