# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0005_auto_20160321_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='cor_coef',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='p_value',
            field=models.FloatField(null=True),
        ),
    ]
