# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0006_auto_20160321_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.RemoveField(
            model_name='visionattr',
            name='face',
        ),
        migrations.DeleteModel(
            name='Face',
        ),
        migrations.DeleteModel(
            name='VisionAttr',
        ),
    ]
